name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12.5
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.5

      - name: install packages
        run: make install

      - name: lint
        run: make lint

      - name: test
        run: make test

      - name: format
        run: make format
